[package]
name = "rmus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.27.0", features = ["event-stream"] }
rodio = "0.18.0"
rusty-chromaprint = "0.2.0"
serde = "1.0.200"
